FROM node:21-alpine

WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


EXPOSE 5173


CMD ["npm", "run", "preview", "--", "--port", "5173", "--host"]